# Generated by Django 5.1.4 on 2025-01-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='Autres Projets', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(max_length=200),
        ),
    ]
