# Generated by Django 5.1.4 on 2025-01-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_image'),
    ]

    operations = [
    ]
