# Generated by Django 5.1.4 on 2025-01-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20250114_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notebook',
            field=models.FileField(blank=True, null=True, upload_to='notebooks/'),
        ),
    ]
