# Generated by Django 5.1.4 on 2025-01-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notebook_html',
            field=models.FileField(blank=True, null=True, upload_to='notebooks/html/'),
        ),
    ]
