# Generated by Django 5.1.15 on 2026-01-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_notebook_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('ref_domain', models.CharField(blank=True, db_index=True, max_length=120)),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('browser', models.CharField(blank=True, db_index=True, max_length=30)),
                ('visitor_day', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['ts', 'path'], name='projects_pa_ts_fe3bfe_idx'), models.Index(fields=['ts', 'ref_domain'], name='projects_pa_ts_4665f9_idx')],
            },
        ),
    ]
